INSERT INTO subscription(name, price)
VALUES ('SUBSCRIPTION_FREE', 0.00),
       ('SUBSCRIPTION_BASIC', 9.99),
       ('SUBSCRIPTION_PREMIUM', 19.99),
       ('SUBSCRIPTION_ULTIMATE', 29.99),
       ('SUBSCRIPTION_ENTERPRISE', -1.00);
