import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { MdStar } from 'react-icons/md';

import { Text, Image as Picture, Badge, Box, Center, Flex } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Center h="100vh">
          <Box p="5" maxW="320px" borderWidth="1px">
            <Picture borderRadius="md" src="https://bit.ly/2k1H1t6" />
            <Flex align="baseline" mt={2}>
              <Badge colorScheme="pink">Plus</Badge>
              <Text
                ml={2}
                textTransform="uppercase"
                fontSize="sm"
                fontWeight="bold"
                color="pink.800"
              >
                Verified &bull; Cape Town
              </Text>
            </Flex>
            <Text mt={2} fontSize="xl" fontWeight="semibold" lineHeight="short">
              Modern, Chic Penthouse with Mountain, City & Sea Views
            </Text>
            <Text mt={2}>$119/night</Text>
            <Flex mt={2} align="center">
              <Box as={MdStar} color="orange.400" />
              <Text ml={1} fontSize="sm">
                <b>4.84</b> (190)
              </Text>
            </Flex>
          </Box>
        </Center>
      </main>
    </>
  );
}
